name: kicks_for_nerds
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker:
  file_picker: ^3.0.1
  uuid: ^3.0.4


  cupertino_icons: ^1.0.2
  firebase_core: ^1.4.0
  firebase_auth: ^3.0.1
  firebase_database: ^7.1.2
  firebase_storage: ^8.0.3
  provider: ^5.0.0
 
  

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true


  assets:
    - images/



  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Light.ttf
          weight: 100
        - asset: fonts/Roboto-Regular.ttf
          weight: 200
        - asset: fonts/Roboto-Medium.ttf
          weight: 300
        - asset: fonts/Roboto-Bold.ttf
          weight: 400
    
     
    - family: Comfortaa
      fonts:
        - asset: fonts/Comfortaa-Regular.ttf
          weight: 100

